### ISSUE TITLE
Feature request: ability to provide secret environment variables

### ISSUE THREAD

**Issue by maelle** [ropensci/docs#1]
:speak_no_evil:

**Comment by jeroen** [comment]
I don't think we'll do this. The difference between CI and a repository is that the packages need to work in a standard environment. Just like for example CRAN.

I recommend package authors to precompute (i.e. locally knit) vignettes that require auth or take very long to compute.

**Comment by maelle** [comment]
ok, and cf https://github.com/ropensci/dev_guide/issues/220
