### ISSUE TITLE
If there's no favicon files/no logo, use rOpenSci logo?

### ISSUE THREAD

**Issue by maelle** [ropensci/docs#3]
That's something I was hoping to tell authors to do in the repos, via [rodev::use_ro_favicon()](https://ropenscilabs.github.io/rodev/reference/use_ro_favicon.html) but it might be easier to solve it centrally via your docs builder @jeroen: if there's no pkgdown folder with at least one image called favicon (see https://github.com/ropenscilabs/rodev/tree/master/pkgdown/favicon) then could you create it before building the website? E.g. https://docs.ropensci.org/cld2/ has no favicon at the moment whereas https://docs.ropensci.org/magick/ does

Likewise, if there's no logo.png in man/figures, before building the website one could be created (cf https://github.com/ropenscilabs/rodev/tree/master/man/figures) so that pkgdown would use it? If there's a logo, pkgdown uses it when creating the Twitter/OpenGraph metadata (note that this could change slightly in the future i.e. a different filename for the logo for Twitter/OpenGraph https://github.com/r-lib/pkgdown/issues/936) so Twitter cards would feature the rOpenSci logo instead of nothing.

**Comment by jeroen** [comment]
Note that sites hosted under `https://docs.ropensci.org` which do not have custom icons will default to the global favicons from the website, for example `https://docs.ropensci.org/favicon.ico`

**Comment by jeroen** [comment]
Global favicons for `docs.ropensci.org` are in the [github repo](https://github.com/ropensci-docs/ropensci-docs.github.io). These are automatically used for each site under `docs.ropensci.org` so I don't think there is any need for customizing these.

**Comment by maelle** [comment]
yes for favicons, but no for Twitter metadata! :wink: I mean

> Likewise, if there's no logo.png in man/figures, before building the website one could be created (cf https://github.com/ropenscilabs/rodev/tree/master/man/figures) so that pkgdown would use it? If there's a logo, pkgdown uses it when creating the Twitter/OpenGraph metadata (note that this could change slightly in the future i.e. a different filename for the logo for Twitter/OpenGraph r-lib/pkgdown#936) so Twitter cards would feature the rOpenSci logo instead of nothing.

**Comment by maelle** [comment]
Dup of https://github.com/ropensci/rotemplate/issues/21
