### ISSUE TITLE
What happens if a package has no .norodocs file then gets one

### ISSUE THREAD

**Issue by maelle** [ropensci/docs#4]
is the old version of the website of that package removed?

**Comment by jeroen** [comment]
I guess one of us needs to delete it manually from: https://github.com/ropensci-docs

**Comment by maelle** [comment]
Ok so should I add this guidance to the dev guide or wait for folks to ask? I.e. would explaining how to opt out encourage opting out (which would be sad)?

**Comment by jeroen** [comment]
At the all hands meeting, we discussed that there is really no good argument for letting people opt-out of documentation. So let's not worry about as long as it doesn't come up and somebody really wants to opt out.

**Comment by maelle** [comment]
ok. btw we should delete https://docs.ropensci.org/dashboard/
